import type { KnowledgeDocument } from './types';

/** Seed corpus — local markdown/JSON-shaped content for the stub store (not production RAG). */
export const STUB_KNOWLEDGE_DOCUMENTS: readonly KnowledgeDocument[] = [
  {
    id: 'doc-leave-policy',
    title: 'Leave Policy',
    summary: 'Annual, casual, and sick leave entitlements, approval flow, and carry-forward rules.',
    body: `Employees receive Annual, Casual, and Sick leave as per role and tenure.
Leave requests are submitted in OneCare / HRIS and approved by the reporting manager.
Carry-forward of Annual leave is capped per country calendar year (default India: 5 days).
Weekends and listed holidays are excluded from leave day counts unless half-day rules apply.`,
    domain: 'hr',
    category: 'leave',
    topics: ['leave policy', 'carry forward', 'approval'],
    tags: ['leave', 'policy', 'hr'],
    documentType: 'policy',
    section: 'Overview',
    lastUpdated: '2026-01-15',
    relatedIds: ['doc-maternity', 'doc-wfh', 'doc-handbook'],
    faqs: [
      'How many annual leaves do I get?',
      'Can I carry forward my leave?',
      'Who approves leave?',
    ],
    country: 'India',
    url: '/knowledge/leave-policy',
  },
  {
    id: 'doc-maternity',
    title: 'Maternity & Paternity Leave',
    summary: 'Parental leave entitlements and eligibility.',
    body: `Maternity leave: eligible employees receive 26 weeks of paid maternity leave as per applicable law and company policy.
Paternity leave: eligible employees receive 5 working days of paid paternity leave around the birth or adoption event.
Notify HR and your manager at least 4 weeks in advance when possible.`,
    domain: 'hr',
    category: 'leave',
    topics: ['maternity', 'paternity', 'parental leave'],
    tags: ['leave', 'maternity', 'paternity'],
    documentType: 'policy',
    section: 'Parental leave',
    lastUpdated: '2026-02-01',
    relatedIds: ['doc-leave-policy'],
    faqs: ['How many maternity leaves do I get?', 'What about paternity leave?'],
    country: 'India',
    url: '/knowledge/maternity-paternity',
  },
  {
    id: 'doc-wfh',
    title: 'Work From Home / Hybrid Policy',
    summary: 'Eligibility and expectations for remote and hybrid work.',
    body: `Eligible employees may work from home up to 2 days per week with manager approval, unless a team policy is stricter.
Core collaboration hours remain 11:00–16:00 local time.
Attendance must still be recorded; WFH does not replace leave for full-day absence.`,
    domain: 'hr',
    category: 'attendance',
    topics: ['work from home', 'wfh', 'hybrid'],
    tags: ['wfh', 'hybrid', 'attendance'],
    documentType: 'policy',
    section: 'Hybrid work',
    lastUpdated: '2025-11-20',
    relatedIds: ['doc-leave-policy', 'doc-attendance'],
    faqs: ['Can I work from home?', 'How many WFH days are allowed?'],
    url: '/knowledge/wfh-policy',
  },
  {
    id: 'doc-attendance',
    title: 'Attendance Policy',
    summary: 'Clock-in expectations and regularization.',
    body: `Employees should clock in/out using the approved attendance system.
Missed punches can be regularized within 7 days with manager approval.
Persistent late arrivals may trigger coaching per the attendance SOP.`,
    domain: 'hr',
    category: 'attendance',
    topics: ['attendance', 'regularization', 'clock in'],
    tags: ['attendance'],
    documentType: 'policy',
    section: 'Attendance',
    lastUpdated: '2025-10-01',
    relatedIds: ['doc-wfh'],
    faqs: ['How do I regularize attendance?'],
    url: '/knowledge/attendance-policy',
  },
  {
    id: 'doc-reimbursement',
    title: 'Expense Reimbursement Guide',
    summary: 'How to submit and track expense reimbursements.',
    body: `Submit claims in the expense system within 30 days of spend.
Attach itemized receipts. Manager approval is required before Finance processes payment.
Typical cycle: 7–10 business days after approval.
Internet allowance claims follow the Benefits → Internet Allowance policy.`,
    domain: 'finance',
    category: 'reimbursement',
    topics: ['reimbursement', 'expense claim'],
    tags: ['reimbursement', 'finance'],
    documentType: 'guide',
    section: 'Claims',
    lastUpdated: '2026-03-01',
    relatedIds: ['doc-internet', 'doc-expense'],
    faqs: ['How does reimbursement work?', 'How long do reimbursements take?'],
    url: '/knowledge/reimbursement',
  },
  {
    id: 'doc-expense',
    title: 'Expense Policy',
    summary: 'Eligible expenses and limits.',
    body: `Business travel, client entertainment (within limits), and approved learning fees may be claimed.
Personal commuting is not reimbursable unless covered by a specific allowance.`,
    domain: 'finance',
    category: 'expense',
    topics: ['expense policy'],
    tags: ['expense', 'finance'],
    documentType: 'policy',
    section: 'Eligible expenses',
    lastUpdated: '2026-01-10',
    relatedIds: ['doc-reimbursement'],
    faqs: ['What expenses can I claim?'],
    url: '/knowledge/expense-policy',
  },
  {
    id: 'doc-internet',
    title: 'Internet Allowance',
    summary: 'Monthly internet stipend eligibility and claim process.',
    body: `Eligible hybrid/remote employees may claim a monthly internet allowance up to the published cap.
Submit via reimbursement with the ISP invoice once per month.`,
    domain: 'hr',
    category: 'benefits',
    topics: ['internet allowance', 'benefits'],
    tags: ['internet', 'benefits'],
    documentType: 'policy',
    section: 'Internet allowance',
    lastUpdated: '2025-12-12',
    relatedIds: ['doc-reimbursement', 'doc-benefits'],
    faqs: ['Can I claim internet allowance?'],
    url: '/knowledge/internet-allowance',
  },
  {
    id: 'doc-benefits',
    title: 'Employee Benefits Overview',
    summary: 'Health, travel, insurance, and learning benefits at a glance.',
    body: `Benefits include group health insurance, optional top-ups, travel insurance for business trips,
learning stipend, and location-specific allowances. Details vary by country and employment type.`,
    domain: 'hr',
    category: 'benefits',
    topics: ['benefits', 'health', 'travel', 'insurance', 'learning'],
    tags: ['benefits'],
    documentType: 'handbook',
    section: 'Benefits',
    lastUpdated: '2026-01-05',
    relatedIds: ['doc-insurance', 'doc-internet'],
    faqs: ['What benefits do we offer?'],
    url: '/knowledge/benefits',
  },
  {
    id: 'doc-insurance',
    title: 'Group Health Insurance',
    summary: 'Coverage summary and how to raise a claim.',
    body: `Group medical insurance covers employee + dependents as defined in the benefits booklet.
Cashless network hospitals are listed on the insurer portal. Notify HR Benefits for additions.`,
    domain: 'hr',
    category: 'insurance',
    topics: ['health insurance', 'medical'],
    tags: ['insurance', 'health'],
    documentType: 'policy',
    section: 'Medical cover',
    lastUpdated: '2026-02-20',
    relatedIds: ['doc-benefits'],
    faqs: ['How do I use health insurance?'],
    url: '/knowledge/insurance',
  },
  {
    id: 'doc-probation',
    title: 'Probation Guidelines',
    summary: 'Expectations and outcomes during probation.',
    body: `New joiners typically serve a probation period (commonly 3–6 months).
During probation, leave accruals may differ and confirmation depends on performance feedback.
Managers complete a confirmation review before the probation end date.`,
    domain: 'hr',
    category: 'employment',
    topics: ['probation'],
    tags: ['probation', 'employment'],
    documentType: 'policy',
    section: 'Probation',
    lastUpdated: '2025-09-01',
    relatedIds: ['doc-joining', 'doc-leave-policy'],
    faqs: ['What happens during probation?'],
    url: '/knowledge/probation',
  },
  {
    id: 'doc-joining',
    title: 'Joining & Onboarding',
    summary: 'First-week checklist for new employees.',
    body: `Complete HR paperwork, IT asset setup, mandatory compliance training, and team introductions in week one.
Your buddy and HRBP are primary contacts for joining questions.`,
    domain: 'hr',
    category: 'joining',
    topics: ['joining', 'onboarding'],
    tags: ['onboarding'],
    documentType: 'guide',
    section: 'First week',
    lastUpdated: '2026-01-20',
    relatedIds: ['doc-probation', 'doc-handbook'],
    faqs: ['What do I need on day one?'],
    url: '/knowledge/joining',
  },
  {
    id: 'doc-relocation',
    title: 'Relocation Support',
    summary: 'When relocation assistance is available.',
    body: `Relocation support may be offered for role-driven office moves and approved transfers.
Coverage can include temporary housing and moving logistics within published caps.
Request via HRBP; Finance processes approved claims.`,
    domain: 'hr',
    category: 'benefits',
    topics: ['relocation'],
    tags: ['relocation', 'benefits'],
    documentType: 'policy',
    section: 'Relocation',
    lastUpdated: '2025-08-15',
    relatedIds: ['doc-benefits', 'doc-reimbursement'],
    faqs: ['Do we have relocation support?'],
    url: '/knowledge/relocation',
  },
  {
    id: 'doc-code-of-conduct',
    title: 'Code of Conduct',
    summary: 'Expected workplace behavior and ethics standards.',
    body: `The Code of Conduct covers integrity, respectful workplace, conflicts of interest, and speaking up.
Report concerns via the ethics hotline or HR. Retaliation for good-faith reports is prohibited.`,
    domain: 'company',
    category: 'compliance',
    topics: ['code of conduct', 'ethics'],
    tags: ['compliance', 'conduct'],
    documentType: 'policy',
    section: 'Standards',
    lastUpdated: '2026-01-01',
    relatedIds: ['doc-handbook'],
    faqs: ['Where can I find the code of conduct?'],
    url: '/knowledge/code-of-conduct',
  },
  {
    id: 'doc-handbook',
    title: 'Employee Handbook',
    summary: 'Index of core company policies for employees.',
    body: `The handbook links leave, attendance, benefits, IT acceptable use, and compliance policies.
Prefer the latest digital handbook over printed copies.`,
    domain: 'company',
    category: 'handbook',
    topics: ['handbook', 'policies'],
    tags: ['handbook'],
    documentType: 'handbook',
    section: 'Index',
    lastUpdated: '2026-03-10',
    relatedIds: ['doc-leave-policy', 'doc-code-of-conduct', 'doc-wfh'],
    faqs: ['Where is the employee handbook?'],
    url: '/knowledge/handbook',
  },
  {
    id: 'doc-vpn',
    title: 'VPN Access Guide',
    summary: 'How to connect securely to the corporate network.',
    body: `Install the approved VPN client from the IT software portal.
Sign in with SSO. If connection fails, restart the client and raise an IT ticket.`,
    domain: 'it',
    category: 'vpn',
    topics: ['vpn'],
    tags: ['vpn', 'it'],
    documentType: 'guide',
    section: 'Connect',
    lastUpdated: '2025-11-01',
    relatedIds: ['doc-password'],
    faqs: ['How do I connect to VPN?'],
    url: '/knowledge/vpn',
  },
  {
    id: 'doc-password',
    title: 'Password Reset',
    summary: 'Self-service password and MFA reset steps.',
    body: `Use the identity portal “Forgot password” flow. MFA devices can be reset by IT after identity verification.
Never share passwords or MFA codes.`,
    domain: 'it',
    category: 'password',
    topics: ['password', 'mfa'],
    tags: ['password', 'it'],
    documentType: 'guide',
    section: 'Reset',
    lastUpdated: '2025-12-01',
    relatedIds: ['doc-vpn'],
    faqs: ['How do I reset my password?'],
    url: '/knowledge/password-reset',
  },
  {
    id: 'doc-referral',
    title: 'Employee Referral Program',
    summary: 'How referrals and rewards work.',
    body: `Submit referrals via the careers portal. Rewards are paid after the hire completes the eligibility period.
Internal job applications use a separate internal mobility process.`,
    domain: 'recruitment',
    category: 'referral',
    topics: ['referral'],
    tags: ['referral', 'recruitment'],
    documentType: 'policy',
    section: 'Referrals',
    lastUpdated: '2026-02-10',
    relatedIds: ['doc-internal-jobs'],
    faqs: ['How does employee referral work?'],
    url: '/knowledge/referral',
  },
  {
    id: 'doc-internal-jobs',
    title: 'Internal Mobility',
    summary: 'Applying to internal job postings.',
    body: `Employees may apply to internal roles after completing probation unless an exception is approved.
Inform your manager when moving to late-stage interviews.`,
    domain: 'recruitment',
    category: 'internal_jobs',
    topics: ['internal jobs', 'transfer'],
    tags: ['internal', 'jobs'],
    documentType: 'guide',
    section: 'Apply',
    lastUpdated: '2025-07-01',
    relatedIds: ['doc-referral'],
    faqs: ['How do internal job applications work?'],
    url: '/knowledge/internal-jobs',
  },
  {
    id: 'doc-training',
    title: 'Learning & Training',
    summary: 'Mandatory and optional learning paths.',
    body: `Mandatory compliance training must be completed by the published due date.
Optional role-based learning is available in the LMS. Certification reimbursement follows Learning policy.`,
    domain: 'learning',
    category: 'training',
    topics: ['training', 'lms'],
    tags: ['learning', 'training'],
    documentType: 'guide',
    section: 'Catalog',
    lastUpdated: '2026-01-25',
    relatedIds: ['doc-certification'],
    faqs: ['What training is available?'],
    url: '/knowledge/training',
  },
  {
    id: 'doc-certification',
    title: 'Certification Reimbursement',
    summary: 'Rules for professional certification funding.',
    body: `Pre-approve certifications with your manager. Reimbursement requires proof of passing and receipts.
Annual caps apply per employee grade.`,
    domain: 'learning',
    category: 'certification',
    topics: ['certification'],
    tags: ['certification', 'learning'],
    documentType: 'policy',
    section: 'Funding',
    lastUpdated: '2025-06-15',
    relatedIds: ['doc-training', 'doc-reimbursement'],
    faqs: ['Do we reimburse certifications?'],
    url: '/knowledge/certification',
  },
  {
    id: 'doc-leave-appeal',
    title: 'Leave Decision Escalation',
    summary: 'What to do if a leave request is rejected.',
    body: `If your manager rejects a leave request, review the rejection reason in ESS.
You may discuss alternatives (different dates or leave type) with your manager.
For policy disputes, contact your HRBP — do not invent approvals outside the workflow.`,
    domain: 'hr',
    category: 'leave',
    topics: ['leave rejected', 'escalation', 'appeal'],
    tags: ['leave', 'escalation'],
    documentType: 'sop',
    section: 'Escalation',
    lastUpdated: '2025-10-20',
    relatedIds: ['doc-leave-policy'],
    faqs: ['My manager rejected my leave. What can I do?'],
    url: '/knowledge/leave-escalation',
  },
];
